# 🚀 OqoolAI Cloud IDE - Docker Compose Configuration

version: '3.8'

services:
  # 🌐 Main Application
  oqoolai-cloud-ide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oqoolai-cloud-ide
    restart: unless-stopped
    ports:
      - "3000:3001"  # Map host:3000 to container:3001
    environment:
      - NODE_ENV=production
      - PORT=3001
      - AI_API_URL=${AI_API_URL:-http://localhost:8000}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@postgres:5432/oqoolai}
    depends_on:
      - redis
      - postgres
    volumes:
      - ./data/projects:/app/data/projects
      - ./data/logs:/app/logs
    networks:
      - oqoolai-network
    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 🔄 Redis Cache
  redis:
    image: redis:7-alpine
    container_name: oqoolai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-oqoolai2024}
    networks:
      - oqoolai-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # 🗄️ PostgreSQL Database  
  postgres:
    image: postgres:15-alpine
    container_name: oqoolai-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=oqoolai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oqoolai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d oqoolai"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🔍 Development Tools (Optional)
  adminer:
    image: adminer:latest
    container_name: oqoolai-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - oqoolai-network
    profiles:
      - dev
      - debug

  # 📊 Redis Commander (Optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: oqoolai-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-oqoolai2024}
    depends_on:
      - redis
    networks:
      - oqoolai-network
    profiles:
      - dev
      - debug

  # 🔄 Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: oqoolai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./data/logs/nginx:/var/log/nginx
    depends_on:
      - oqoolai-cloud-ide
    networks:
      - oqoolai-network
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  oqoolai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16